require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

###########
# BUNDLER #
###########

Bundler:
  Enabled: true

Bundler/GemComment:
  Enabled: true
  OnlyFor: ["bitbucket", "gist", "git", "github", "source"]
  IgnoredGems: []

###########
# GEMSPEC #
###########

Gemspec:
  Enabled: true

##########
# LAYOUT #
##########

Layout:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: true
  EnforcedStyleForExponentOperator: space

# Rufo already agrees with these

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

# Make these agree with Rufo

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space

Layout/HeredocIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

########
# LINT #
########

Lint:
  Enabled: true

# This one was giving a false positive
Lint/RedundantCopDisableDirective:
  Enabled: false

###########
# METRICS #
###########

Metrics:
  Enabled: true

Metrics/MethodLength:
  Enabled: true
  Max: 50

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Max: 25
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 15

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 15

Metrics/AbcSize:
  Enabled: true
  Max: 30

##########
# NAMING #
##########

Naming:
  Enabled: true

############
# SECURITY #
############

Security:
  Enabled: true

#########
# STYLE #
#########

Style:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: braces_for_chaining
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true

Style/NumericPredicate:
  Enabled: true
  EnforcedStyle: predicate

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# Can never agree with Rufo

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

#########
# RSPEC #
#########

RSpec:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

###############
# PERFORMANCE #
###############

Performance:
  Enabled: true
